language: cpp
compiler: gcc
addons:
  apt:
    packages:
    - libmysql++3:i386
    - gcc-4.6-multilib
    - g++-4.6-multilib
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - make NIGHTLY=1 -f makefile
after_success:
  "curl -T spheresvr -u $FTP_USER:$FTP_PASSWORD ftp://revenger.6te.net/sphere_nightly"
notifications:
  email: false