language: cpp
compiler: gcc
addons:
  apt:
    packages:
    - gcc-4.6-multilib
    - g++-4.6-multilib
    - linux-libc-dev
    - libmysqld-dev
    - libmysql++-dev
    - libmysqlclient-dev
script: make