language: cpp
compiler: gcc
addons:
  apt:
    packages:
    - gcc-4.6-multilib
    - g++-4.6-multilib
    - linux-libc-dev
    - libmysqld-dev
    - libmysql++-dev
    - libmysqlclient-dev
sudo: required
before_script:
  - sudo ln -s /usr/include/i386-linux-gnu/asm /usr/include/asm
script: make