version: 0.56.4.{build}
configuration: Nightly
pull_requests:
  do_not_increment_build_number: true
build:
  project: GraySvr.vcxproj
  verbosity: minimal
artifacts:
- path: $(configuration)\SphereSvr.exe
  name: SphereSvr