version: 0.56.4.{build}
configuration: Nightly
pull_requests:
  do_not_increment_build_number: true
build:
  project: GraySvr.vcxproj
  verbosity: minimal
after_build:
- cmd: 7z a SphereSvr-Win32.zip %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\SphereSvr.exe
artifacts:
- path: SphereSvr-Win32.zip
  name: SphereSvr
deploy:
  provider: FTP
  protocol: ftp
  host: revenger.6te.net
  username:
    secure: FeZDtksWkubb3mE/+X03khg1vgiS2xWso3ESRUoE2ZA=
  password:
    secure: WBZe/32QQ9iMEmGnfrSKmA==
  artifact: SphereSvr-Win32.zip