version: 0.56.4.{build}
configuration: Nightly
pull_requests:
  do_not_increment_build_number: true
build:
  project: GraySvr.vcxproj
  verbosity: minimal
after_build:
- cmd: 7z a SphereSvr-Win32.zip %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\SphereSvr.exe \src\sphere.ini \src\sphereCrypt.ini
artifacts:
- path: SphereSvr-Win32.zip
  name: SphereSvr
deploy:
  provider: FTP
  protocol: ftp
  host: spherecommunity.net
  username:
    secure: UAZaqnbj2s8C/ObEXIg6xA==
  password:
    secure: 4QZxkFb+hk0DMpbglPiI2KLs3uL7W2Iz/uarUbkxeTU=
  artifact: SphereSvr-Win32.zip